server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/users/**,/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER
                fallbackuri: forward:/userFallBack
        - id: DEPARTEMENT
          uri: lb://DEPARTEMENT
          predicates:
            - Path=/hr/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTEMENT
                fallbackuri: forward:/departmentFallBack

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info

