server:
  port: 9002

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jdan116/config-server
          clone-on-start: true




